version: '3.8'
services:
  ai:
    build: ./nexus-ai
    ports:
      - "8000:8000"
  backend:
    build: ./nexus-backend
    ports:
      - "8080:8080"
    environment:
      - AI_BASE_URL=https://aiservice-production-acab.up.railway.app
      - DATABASE_URL=postgres://postgres:hTckoowSOUVGSbZXigsxWBVXxlXYFAfu@shinkansen.proxy.rlwy.net:57937/railway
      - API_BASE_URL=https://nexus-production-2e34.up.railway.app
    depends_on:
      - ai
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hTckoowSOUVGSbZXigsxWBVXxlXYFAfu
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 