version: '3.8'
services:
  ai:
    build: ./nexus-ai
    ports:
      - "8000:8000"
  backend:
    build: ./nexus-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - AI_BASE_URL=https://aiservice-production-acab.up.railway.app
      - DATABASE_URL=postgres://postgres:hTckoowSOUVGSbZXigsxWBVXxlXYFAfu@shinkansen.proxy.rlwy.net:57937/railway
      - API_BASE_URL=https://nexus-production-2e34.up.railway.app
      - DB_HOST=shinkansen.proxy.rlwy.net
      - DB_PORT=57937
      - DB_NAME=railway
      - DB_USER=postgres
      - DB_PASSWORD=hTckoowSOUVGSbZXigsxWBVXxlXYFAfu
    depends_on:
      - ai
# Using Railway database instead of local database